# Generated by Django 3.2.2 on 2021-05-15 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, primary_key=True, serialize=False, unique=True, verbose_name='email')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Last Login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('hide_email', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(default=0)),
                ('duration', models.TimeField(default='08:00')),
                ('dateTime', models.DateField(default='1994-05-14')),
                ('menuOption', models.CharField(default='NULL', max_length=256)),
                ('latitude', models.FloatField(default=0)),
                ('longditude', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NULL', max_length=256)),
                ('location', models.CharField(default='NULL', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NULL', max_length=60)),
                ('lastname', models.CharField(default='NULL', max_length=60)),
                ('phone', models.IntegerField(default=0)),
                ('address', models.CharField(default='NULL', max_length=150)),
                ('birth_date', models.DateField(default='1994-05-14')),
                ('account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NULL', max_length=256)),
                ('age', models.CharField(default='NULL', max_length=256)),
                ('endangered', models.BooleanField(blank=True, default=False, null=True)),
                ('seeds', models.BooleanField(blank=True, default=False, null=True)),
                ('User', models.ForeignKey(blank=True, default='NULL', null=True, on_delete=django.db.models.deletion.SET_NULL, to='voicesystem.user')),
                ('tree', models.ForeignKey(blank=True, default='NULL', null=True, on_delete=django.db.models.deletion.SET_NULL, to='voicesystem.seed')),
            ],
        ),
        migrations.CreateModel(
            name='Menuoptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treeSelection', models.CharField(default='NULL', max_length=256)),
                ('seedsConfirmation', models.BooleanField(blank=True, default=False, null=True)),
                ('contactingpermission', models.BooleanField(blank=True, default=False, null=True)),
                ('triangulationPermission', models.BooleanField(blank=True, default=False, null=True)),
                ('call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voicesystem.call')),
            ],
        ),
        migrations.AddField(
            model_name='call',
            name='User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voicesystem.user'),
        ),
    ]
