# Generated by Django 3.2.2 on 2021-05-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voicesystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='duration',
            field=models.DurationField(default='NULL'),
        ),
    ]
